name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          cd backend
          npm install

      - name: Bump version and build
        run: |
          cd backend
          npm version patch --no-git-tag-version

      - name: Update version file
        run: |
          cd backend
          VERSION=$(node -p "require('./package.json').version")
          BUILD=$(($(jq -r '.build' version.json) + 1))
          echo "{\"version\": \"$VERSION\", \"build\": \"$BUILD\"}" > version.json

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd backend
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add version.json package.json package-lock.json
          git commit -m "Backend: Bump version to ${VERSION}, Build ${BUILD}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kreotiff-dev/gangster_bank.git
          git push origin HEAD:main

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH key
        run: |
          ssh -o StrictHostKeyChecking=no deploy@37.46.129.245 "echo 'SSH Key is working'"

      - name: Deploy to server
        run: |
          ssh deploy@37.46.129.245 "
            source ~/.nvm/nvm.sh && \
            cd /var/www/gbank/backend && \
            git reset --hard HEAD && \
            git pull && \
            npm install && \
            pm2 stop gbank_back || true && \
            pm2 delete gbank_back || true && \
            NODE_ENV=production pm2 start index.js --name gbank_back"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
